# This is a script to make it easier to generate gEDA footprints.
# Make a .in file with lines of the following forms:
#   pin x y hole_r copper_r "label"
#   pad x1 x2 y1 y2 "label"
#   line x1 x2 y1 y2
#
# Any of the coordinates/diameters can include a unit. So, you can say:
#   pin 1_mm 2_in 0.35_mm 1_mm "1"
# By default, units are PCB's internal units.

use Math::Round;

my %units = (
	'mm' => 3937,
	'in' => 100000,
		);
sub unit
{
	my $var=shift;
	@u=split /_/,$var;
	if($u[1])
	{
		$conv=$units{$u[1]} or die "Invalid unit $u[1]";
		return round($u[0]*$conv);
	} else {
		return $u[0];
	}
}

print "# This file was generated by gedapre.pl. Edit the corresponding .in\n";
print "# file, not this one!\n\n";
print "Element[0x00000000 \"\" \"\" \"\" 1000 1000 0 0 0 100 0x00000000]\n(\n";

while(<>)
{
	my @a=split;
	if($a[0] eq 'line')
	{
		my $x1=unit($a[1]);
		my $x2=unit($a[2]);
		my $y1=unit($a[3]);
		my $y2=unit($a[4]);

		if($x2<$x1) { ($x1,$x2)=($x2,$x1); }
		if($y2<$y1) { ($y1,$y2)=($y2,$y1); }
		
		if($y1 == $y2)
		{
			$x1=$x1+500;
			$x2=$x2-500;
		} else {
			$y1=$y1+500;
			$y2=$y2-500;
		}
		print "  ElementLine [$x1 $y1 $x2 $y2 1000]\n";
	}	if($a[0] eq 'pin')	{
		my $x=unit($a[1]);
		my $y=unit($a[2]);
		my $r1=unit($a[3]);
		my $r2=unit($a[4]);
		my $num=$a[5];
		my $mask=$r2;

		print "  Pin [$x $y $r2 1600 $mask $r1 \"\" $num 0x00004001]\n";
	} elsif($a[0] eq 'pad')	{
		my $x1=unit($a[1]);
		my $x2=unit($a[2]);
		my $y1=unit($a[3]);
		my $y2=unit($a[4]);
		my $num=$a[5];
		#print "$x1,$y1,$x2,$y2";
		
		if($x2<$x1) { ($x1,$x2)=($x2,$x1); }
		if($y2<$y1) { ($y1,$y2)=($y2,$y1); }

		my $w=$x2-$x1;
		my $h=$y2-$y1;

		if($w>$h)
		{
			my $thickness=$h;
			my $xx1=$x1+round($thickness/2);
			my $xx2=$x2-round($thickness/2);
			my $y=round(($y1+$y2)/2);

			my $clearance=$thickness+1200;

			print "  Pad [$xx1 $y $xx2 $y $thickness 1200 $clearance \"\" $num 0x00004101]\n";
		} else {
			my $thickness=$w;
			my $yy1=$y1+round($thickness/2);
			my $yy2=$y2-round($thickness/2);
			my $x=round(($x1+$x2)/2);

			my $clearance=$thickness+1200;

			print "  Pad [$x $yy1 $x $yy2 $thickness 1200 $clearance \"\" $num 0x00004101]\n";

		}
	}
}

print ")";
